/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpectaclesRouteImport } from './routes/spectacles'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsIdIndexRouteImport } from './routes/patients.$id.index'
import { Route as PatientsIdEditRouteImport } from './routes/patients.$id.edit'
import { Route as ReceiptsKindIdRouteImport } from './routes/receipts.$kind.$id'
import { Route as PatientsIdVisitsNewRouteImport } from './routes/patients.$id.visits.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectaclesRoute = SpectaclesRouteImport.update({
  id: '/spectacles',
  path: '/spectacles',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdIndexRoute = PatientsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsIdEditRoute = PatientsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PatientsIdRoute,
} as any)
const ReceiptsKindIdRoute = ReceiptsKindIdRouteImport.update({
  id: '/receipts/$kind/$id',
  path: '/receipts/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdVisitsNewRoute = PatientsIdVisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => PatientsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/spectacles': typeof SpectaclesRoute
  '/visits': typeof VisitsRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/receipts/$kind/$id': typeof ReceiptsKindIdRoute
  '/patients/$id/': typeof PatientsIdIndexRoute
  '/patients/$id/visits/new': typeof PatientsIdVisitsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/spectacles': typeof SpectaclesRoute
  '/visits': typeof VisitsRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients': typeof PatientsIndexRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/receipts/$kind/$id': typeof ReceiptsKindIdRoute
  '/patients/$id': typeof PatientsIdIndexRoute
  '/patients/$id/visits/new': typeof PatientsIdVisitsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/spectacles': typeof SpectaclesRoute
  '/visits': typeof VisitsRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/patients/$id/edit': typeof PatientsIdEditRoute
  '/receipts/$kind/$id': typeof ReceiptsKindIdRoute
  '/patients/$id/': typeof PatientsIdIndexRoute
  '/patients/$id/visits/new': typeof PatientsIdVisitsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/medicines'
    | '/patients'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/spectacles'
    | '/visits'
    | '/patients/$id'
    | '/patients/new'
    | '/patients/'
    | '/patients/$id/edit'
    | '/receipts/$kind/$id'
    | '/patients/$id/'
    | '/patients/$id/visits/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/medicines'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/spectacles'
    | '/visits'
    | '/patients/new'
    | '/patients'
    | '/patients/$id/edit'
    | '/receipts/$kind/$id'
    | '/patients/$id'
    | '/patients/$id/visits/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/medicines'
    | '/patients'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/spectacles'
    | '/visits'
    | '/patients/$id'
    | '/patients/new'
    | '/patients/'
    | '/patients/$id/edit'
    | '/receipts/$kind/$id'
    | '/patients/$id/'
    | '/patients/$id/visits/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MedicinesRoute: typeof MedicinesRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SpectaclesRoute: typeof SpectaclesRoute
  VisitsRoute: typeof VisitsRoute
  ReceiptsKindIdRoute: typeof ReceiptsKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectacles': {
      id: '/spectacles'
      path: '/spectacles'
      fullPath: '/spectacles'
      preLoaderRoute: typeof SpectaclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id/': {
      id: '/patients/$id/'
      path: '/'
      fullPath: '/patients/$id/'
      preLoaderRoute: typeof PatientsIdIndexRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/$id/edit': {
      id: '/patients/$id/edit'
      path: '/edit'
      fullPath: '/patients/$id/edit'
      preLoaderRoute: typeof PatientsIdEditRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/receipts/$kind/$id': {
      id: '/receipts/$kind/$id'
      path: '/receipts/$kind/$id'
      fullPath: '/receipts/$kind/$id'
      preLoaderRoute: typeof ReceiptsKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/visits/new': {
      id: '/patients/$id/visits/new'
      path: '/visits/new'
      fullPath: '/patients/$id/visits/new'
      preLoaderRoute: typeof PatientsIdVisitsNewRouteImport
      parentRoute: typeof PatientsIdRoute
    }
  }
}

interface PatientsIdRouteChildren {
  PatientsIdEditRoute: typeof PatientsIdEditRoute
  PatientsIdIndexRoute: typeof PatientsIdIndexRoute
  PatientsIdVisitsNewRoute: typeof PatientsIdVisitsNewRoute
}

const PatientsIdRouteChildren: PatientsIdRouteChildren = {
  PatientsIdEditRoute: PatientsIdEditRoute,
  PatientsIdIndexRoute: PatientsIdIndexRoute,
  PatientsIdVisitsNewRoute: PatientsIdVisitsNewRoute,
}

const PatientsIdRouteWithChildren = PatientsIdRoute._addFileChildren(
  PatientsIdRouteChildren,
)

interface PatientsRouteChildren {
  PatientsIdRoute: typeof PatientsIdRouteWithChildren
  PatientsNewRoute: typeof PatientsNewRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsIdRoute: PatientsIdRouteWithChildren,
  PatientsNewRoute: PatientsNewRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MedicinesRoute: MedicinesRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SpectaclesRoute: SpectaclesRoute,
  VisitsRoute: VisitsRoute,
  ReceiptsKindIdRoute: ReceiptsKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
